name: Lint

on: push

jobs:
  lint-ruff:
    name: Lint with ruff
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      name: Checkout repository

    - uses: chartboost/ruff-action@v1
      with:
        args: |
          --ignore E101
