name: Release

on:
  workflow_dispatch:

permissions:
  contents: write
  discussions: write
  packages: read

jobs:
  build-linux:
    name: Build Linux binary
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      name: Checkout repository

    - uses: actions/setup-python@v4
      name: Setup Python
      with:
        python-version: '3.11'

    - name: Install requirements
      run: pip install -r requirements.txt

    - name: Get version
      id: get_version
      run: |
        VERSION_NUM=$(python build.py --version)
        echo "VERSION_NUM=${VERSION_NUM}" >> $GITHUB_OUTPUT

    - name: Package binary
      run: python build.py

    - name: Rename binary
      run: mv "${{ github.event.repository.name }}-v${{ steps.get_version.outputs.VERSION_NUM }}" "${{ github.event.repository.name }}-v${{ steps.get_version.outputs.VERSION_NUM }}-linux-x86_64"

    - name: Compress binary
      run: tar -a -c -v -f "${{ github.event.repository.name }}-v${{ steps.get_version.outputs.VERSION_NUM }}-linux-x86_64.zip" "${{ github.event.repository.name }}-v${{ steps.get_version.outputs.VERSION_NUM }}-linux-x86_64"

    - uses: actions/upload-artifact@v3
      name: Upload binary artifact
      with:
        name: linux-binary
        retention-days: 3
        path: "${{ github.event.repository.name }}-v${{ steps.get_version.outputs.VERSION_NUM }}-linux-x86_64.zip"
  
  build-macos:
    name: Build macOS binary
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3
      name: Checkout repository

    - uses: actions/setup-python@v4
      name: Setup Python
      with:
        python-version: '3.11'

    - name: Install requirements
      run: pip install -r requirements.txt

    - name: Get version
      id: get_version
      run: |
        VERSION_NUM=$(python build.py --version)
        echo "VERSION_NUM=${VERSION_NUM}" >> $GITHUB_OUTPUT

    - name: Package binary
      run: python build.py

    - name: Rename binary
      run: mv "${{ github.event.repository.name }}-v${{ steps.get_version.outputs.VERSION_NUM }}.app" "${{ github.event.repository.name }}-v${{ steps.get_version.outputs.VERSION_NUM }}-macos-x86_64.app"

    - name: Compress binary
      run: tar -a -c -v -f "${{ github.event.repository.name }}-v${{ steps.get_version.outputs.VERSION_NUM }}-macos-x86_64.zip" "${{ github.event.repository.name }}-v${{ steps.get_version.outputs.VERSION_NUM }}-macos-x86_64.app"

    - uses: actions/upload-artifact@v3
      name: Upload binary artifact
      with:
        name: macos-binary
        retention-days: 3
        path: "${{ github.event.repository.name }}-v${{ steps.get_version.outputs.VERSION_NUM }}-macos-x86_64.zip"
  
  build-windows:
    name: Build Windows binary
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
      name: Checkout repository

    - uses: actions/setup-python@v4
      name: Setup Python
      with:
        python-version: '3.11'

    - name: Install requirements
      run: pip install -r requirements.txt

    - name: Get version
      shell: bash
      id: get_version
      run: |
        VERSION_NUM=$(python build.py --version)
        echo "VERSION_NUM=${VERSION_NUM}" >> $GITHUB_OUTPUT

    - name: Package binary
      run: python build.py

    - name: Rename binary
      shell: bash
      run: mv "${{ github.event.repository.name }}-v${{ steps.get_version.outputs.VERSION_NUM }}.exe" "${{ github.event.repository.name }}-v${{ steps.get_version.outputs.VERSION_NUM }}-windows-x86_64.exe"

    - name: Compress binary
      run: tar -a -c -v -f "${{ github.event.repository.name }}-v${{ steps.get_version.outputs.VERSION_NUM }}-windows-x86_64.zip" "${{ github.event.repository.name }}-v${{ steps.get_version.outputs.VERSION_NUM }}-windows-x86_64.exe"

    - uses: actions/upload-artifact@v3
      name: Upload binary artifact
      with:
          name: windows-binary
          retention-days: 3
          path: "${{ github.event.repository.name }}-v${{ steps.get_version.outputs.VERSION_NUM }}-windows-x86_64.zip"
  
  publish-release:
    name: Publish GitHub release
    runs-on: ubuntu-latest
    needs:
      [build-linux, build-macos, build-windows]

    steps:
    - uses: actions/checkout@v3
      name: Checkout repository

    - uses: actions/setup-python@v4
      name: Setup Python
      with:
        python-version: '3.11'

    - name: Install requirements
      run: pip install -r requirements.txt

    - name: Get version
      id: get_version
      run: |
        VERSION_NUM=$(python build.py --version)
        echo "VERSION_NUM=${VERSION_NUM}" >> $GITHUB_OUTPUT

    - name: Create binary folders
      run: |
        mkdir -p linux-binary
        mkdir -p macos-binary
        mkdir -p windows-binary

    - name: Download Linux binary
      uses: actions/download-artifact@v3
      with:
        name: linux-binary
        path: linux-binary

    - name: Download macOS binary
      uses: actions/download-artifact@v3
      with:
          name: macos-binary
          path: macos-binary

    - name: Download Windows binary
      uses: actions/download-artifact@v3
      with:
          name: windows-binary
          path: windows-binary

    - name: Extract Linux binary
      run: |
        cd linux-binary
        tar -x -v -f "${{ github.event.repository.name }}-v${{ steps.get_version.outputs.VERSION_NUM }}-linux-x86_64.zip"
        cd ..

    # Don't extract macOS binary, because .app can't be distributed alone as it is a directory (will be distributed as .zip)

    - name: Extract Windows binary
      run: |
        cd windows-binary
        tar -x -v -f "${{ github.event.repository.name }}-v${{ steps.get_version.outputs.VERSION_NUM }}-windows-x86_64.zip"
        cd ..

    - name: Create release
      uses: softprops/action-gh-release@v1
      with:
        body: |
          ### **_${{ github.event.repository.name }}-v${{ steps.get_version.outputs.VERSION_NUM }}_**
        draft: false
        prerelease: false
        files: |
          linux-binary/${{ github.event.repository.name }}-v${{ steps.get_version.outputs.VERSION_NUM }}-linux-x86_64
          macos-binary/${{ github.event.repository.name }}-v${{ steps.get_version.outputs.VERSION_NUM }}-macos-x86_64.zip
          windows-binary/${{ github.event.repository.name }}-v${{ steps.get_version.outputs.VERSION_NUM }}-windows-x86_64.exe
        name: v${{ steps.get_version.outputs.VERSION_NUM }}
        tag_name: v${{ steps.get_version.outputs.VERSION_NUM }}
        fail_on_unmatched_files: true
        token: ${{ secrets.GITHUB_TOKEN }}
