name: Release

on:
  workflow_dispatch:

jobs:
  build-linux:
    name: Build Linux binary
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install requirements
      run: pip install -r requirements.txt

    - name: Get version
      id: get_version
      run: echo "VERSION_NUM=$(python build.py --version)" >> $GITHUB_OUTPUT

    - name: Package binary
      run: python build.py

    - name: Upload binary artifact
      run: |
        ls -l
        echo "${{ steps.get_version.outputs.VERSION_NUM }}"
  
  build-macos:
    name: Build macOS binary
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    - name: Install requirements
      run: pip install -r requirements.txt
    - name: Package binary
      run: python build.py
    - name: Upload binary artifact
      run: ls -l
  
  build-windows:
    name: Build Windows binary
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    - name: Install requirements
      run: pip install -r requirements.txt
    - name: Package binary
      run: python build.py
    - name: Upload binary artifact
      run: ls -l
  
  publish-release:
    name: Publish GitHub release
    runs-on: ubuntu-latest
    needs:
      [build-linux, build-macos, build-windows]
    steps:
    - uses: actions/checkout@v3
    - run: echo "test123"
